name: Publish NuGet Package on Release

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Build, Sign, and Publish to NuGet
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Decode SNK File for signing
      - name: Decode SNK File
        run: echo "$SNK_FILE_BASE64" | base64 --decode > ./src/Wordnik.Client/WordnikClientKey.snk
        env:
          SNK_FILE_BASE64: ${{ secrets.SNK_FILE_BASE64 }}

      # Step 3: Restore, Build, and Pack the NuGet Package
      - name: Build and Pack NuGet Package
        run: |
          dotnet restore ./src/Wordnik.Client/Wordnik.Client.csproj
          dotnet build --configuration Release /p:SignAssemblyCondition=true /p:AssemblyOriginatorKeyFile=WordnikClientKey.snk ./src/Wordnik.Client/Wordnik.Client.csproj
          dotnet pack --configuration Release ./src/Wordnik.Client/Wordnik.Client.csproj \
            /p:Version=${{ github.event.release.tag_name }} \
            /p:ReleaseNotes="${{ github.event.release.body }}"

      # Step 4: Publish to NuGet
      - name: Publish to NuGet
        run: |
          dotnet nuget push ./src/Wordnik.Client/bin/Release/*.nupkg \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key "${{ secrets.NUGET_API_KEY }}"
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}